import { generateFiles } from 'fumadocs-openapi';
import { createOpenAPI } from 'fumadocs-openapi/server';
import spec from '../content/openapi/stogas.json';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const openapi = createOpenAPI({
	input() {
		return {
			stogas: spec as any
		};
	}
});

function formatMetaJson(content: Record<string, unknown>) {
	let json = JSON.stringify(content, null, '\t');
	const pages = content.pages;
	if (Array.isArray(pages) && pages.every((page) => typeof page === 'string')) {
		const inlineArray = `[${pages.map((page) => JSON.stringify(page)).join(', ')}]`;
		const inlinePages = `"pages": ${inlineArray}`;
		if (`\t${inlinePages}`.length <= 100) {
			json = json.replace(/\t"pages": \[\n(?:\t\t"[^"]+",?\n)+\t\]/, `\t${inlinePages}`);
		}
	}
	return `${json}\n`;
}

async function main() {
	await generateFiles({
		input: openapi,
		output: path.resolve(__dirname, '../content/reference'),
		per: 'operation',
		groupBy: 'tag',
		meta: {
			folderStyle: 'separator'
		},
		beforeWrite: (files) => {
			for (const file of files) {
				if (file.path.endsWith('meta.json')) {
					try {
						let content = JSON.parse(file.content);
						if (file.path === 'meta.json') {
							content = {
								title: 'API Reference',
								root: true,
								pages: [
									'index',
									'---Catalog---',
									'...catalog',
									'---Models---',
									'...openai-compatible',
									'---Other Endpoints---',
									'...',
									'---Gateway---',
									'provider-behavior',
									'security'
								]
							};
						}
						content.pages = content.pages?.map((page: string) =>
							page === '---Open A I compatible---' ? '---Models---' : page
						);
						if (content.title === 'Open A I compatible') {
							content.title = 'Models';
							content.description = 'Model inference endpoints.';
						}
						if (file.path === path.join('openai-compatible', 'meta.json')) {
							content.title = 'Models';
							content.description = 'Model inference endpoints.';
						}
						if (file.path === path.join('catalog', 'meta.json')) {
							content.title = 'Catalog';
							content.description = 'Public model and routing discovery endpoints.';
						}
						file.content = formatMetaJson(content);
					} catch {
						continue;
					}
				}
				if (file.path.endsWith('.mdx')) {
					// Remove the generated warning comment
					file.content = file.content.replace(
						/{\/\* This file was generated by Fumadocs\. Do not edit this file directly\. Any changes should be made by running the generation command again\. \*\/}/g,
						''
					);

					// Ensure full: true is in frontmatter
					if (!file.content.includes('full: true')) {
						file.content = file.content.replace('---', '---\nfull: true');
					}
					file.content = file.content
						.replace(
							/<APIPage document=\{"([^"]+)"\} operations=\{\[\{"path":"([^"]+)","method":"([^"]+)"\}\]\} \/>/g,
							"<APIPage document={'$1'} operations={[{ path: '$2', method: '$3' }]} />"
						)
						.replace(/\n{3,}/g, '\n\n')
						.trimEnd()
						.concat('\n');
				}
			}
		}
	});
	console.log('API documentation generated.');
}

main().catch(console.error);
