import { generateFiles } from 'fumadocs-openapi';
import { createOpenAPI } from 'fumadocs-openapi/server';
import spec from '../content/openapi/stogas.json';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const openapi = createOpenAPI({
	input() {
		return {
			stogas: spec as any
		};
	}
});

async function main() {
	await generateFiles({
		input: openapi,
		output: path.resolve(__dirname, '../content/reference'),
		per: 'operation',
		groupBy: 'tag',
		meta: true,
		beforeWrite: (files) => {
			for (const file of files) {
				if (file.path.endsWith('meta.json')) {
					try {
						const content = JSON.parse(file.content);
						if (content.title === 'Open A I compatible') {
							content.title = 'OpenAI-compatible';
							file.content = JSON.stringify(content, null, 2);
						}
					} catch {
						continue;
					}
				}
				if (file.path.endsWith('.mdx')) {
					// Remove the generated warning comment
					file.content = file.content.replace(
						/{\/\* This file was generated by Fumadocs\. Do not edit this file directly\. Any changes should be made by running the generation command again\. \*\/}/g,
						''
					);

					// Ensure full: true is in frontmatter
					if (!file.content.includes('full: true')) {
						file.content = file.content.replace('---', '---\nfull: true');
					}
				}
			}
		}
	});
	console.log('API documentation generated.');
}

main().catch(console.error);
